use TranBaSon_T1809E_MXH
GO
CREATE table USER1
(
    ID_USER VARCHAR(20) CONSTRAINT PK_USER PRIMARY KEY ,
    Avatar ntext,
    TrangThaiTK BIT,-- 1: TK mở / 0:TK đóng.
    MatKhau VARCHAR(10),
    Email VARCHAR(50),
    NgaySinh DATE
)
GO
CREATE TABLE Group1
( 
    CheDo BIT,-- 1:Nhóm kín / 0:Nhóm công khai.
    ID_Group VARCHAR(20) CONSTRAINT PK_Group PRIMARY KEY
)
GO
CREATE TABLE ThanhVien
(
    ID_USER VARCHAR(20) CONSTRAINT FK_ThanhVienVsUSER FOREIGN KEY (ID_USER) REFERENCES USER1(ID_USER) ,
    ID_Group VARCHAR(20) CONSTRAINT FK_ThanhVienVsGroup FOREIGN KEY (ID_Group) REFERENCES Group1(ID_Group) ,
    Leader BIT -- 1:là leader / 0:không phải leader.
)
GO
CREATE TABLE Post1
(
    NoiDung ntext,
    Share BIT,--1: share / 0:ko share.
    ID_Post NVARCHAR(20) CONSTRAINT PK_Post PRIMARY KEY ,
    ID_USER VARCHAR(20) CONSTRAINT FP_PostVsUSER FOREIGN KEY (ID_USER) REFERENCES USER1(ID_USER)
)
GO
CREATE TABLE Comment
(   ID_Post NVARCHAR(20) not NULL CONSTRAINT PK_CommentVSPost1 FOREIGN KEY (ID_Post) REFERENCES Post1(ID_
    noiDungCM NVARCHAR(20) not null,
    ID_USER VARCHAR(20) not NULL CONSTRAINT FK_CommentVsUSER FOREIGN KEY (ID_USER) REFERENCES USER1(ID_USER)
)
GO
CREATE TABLE Action1(
    ID_Post NVARCHAR(20) not null CONSTRAINT PK_Action1VsPost1 FOREIGN KEY (ID_Post) REFERENCES Post1(ID_Post),
    ID_USER VARCHAR(20) CONSTRAINT FK_Action1VsUSER1 FOREIGN KEY (ID_USER) REFERENCES USER1(ID_USER),
    Type_Action NVARCHAR(20),
)  
GO
ALTER TABLE Comment 
add ID_USER VARCHAR(20) CONSTRAINT FK_CommentVsUSER FOREIGN KEY (ID_USER) REFERENCES USER1(ID_USER)
GO

