
CREATE DATABASE TranBaSon_thi_DDD
GO
USE TranBaSon_thi_DDD
GO

CREATE TABLE ChuongTrinh
(
	MaCT CHAR(100) NOT NULL,
	TenCT NVARCHAR(100) NOT NULL,
	CONSTRAINT PK_ChuongTrinh PRIMARY KEY (MaCT)
)
CREATE TABLE GiaoVien
(
	MaGV CHAR(100) NOT NULL,
	GVCN NVARCHAR(250) NOT NULL,
	CONSTRAINT PK_MaGV PRIMARY KEY (MaGV),
)
CREATE TABLE Lop
(
	MaLop CHAR(100) NOT NULL,
	ThoiGianHoc NVARCHAR(250) NOT NULL,
	PhongHoc CHAR(100),
	CONSTRAINT PK_maLop PRIMARY KEY (MaLop),
	MaCT CHAR(100) NOT NULL,
	CONSTRAINT FK_lop_maCT FOREIGN KEY (MaCT) REFERENCES dbo.ChuongTrinh,
	MaGV CHAR(100) NOT NULL,
	CONSTRAINT FK_lop_maGV FOREIGN KEY (MaGV) REFERENCES dbo.GiaoVien
)

CREATE TABLE SinhVien
(
	maSV CHAR(100) NOT NULL,
	tenSV NVARCHAR(250) NOT NULL,
	ngaySinh DATE NOT NULL CHECK (YEAR(ngaySinh) < 2001),
	gioitinh nvarCHAR(30) NOT NULL CHECK (gioitinh = 'Nam' OR gioitinh = 'Nữ' OR gioitinh = N'Không xác định'),
	CONSTRAINT PK_maSV PRIMARY KEY (maSV),
	MaLop CHAR(100) NOT NULL,
	CONSTRAINT FK_SinhVien_MaLop FOREIGN KEY (MaLop) REFERENCES Lop(MaLop)
)

